"""
Django settings for Nexo project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=un%k4gy(sn6q5t=9_d9z9)1uj5_sr9=9$^_zf4!q!5#2=nl5a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
     "daphne",
     "channels",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Customer',
    'home',
    'Products',
    'Order',
    'Theme',
    'payment',
    'messaging',
 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Nexo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], # This is the directory where Django will look for templates.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nexo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'nexo',              # Database name
        'USER': 'postgres',          # Username
        'PASSWORD': '2468',        # Password enclosed in quotes
        'HOST': 'localhost',         # Host
        'PORT': '5432',              # Port
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "nexostudypartner@gmail.com"
EMAIL_HOST_PASSWORD = "eikd vuoe ecbw tpgo"

# Debug mode
DEBUG = config("DEBUG", default=False, cast=bool)

# Secret Key
SECRET_KEY = 'django-insecure-abcdefghijklmnopqrstuvwxyz1234567890'

my_email = config("EMAIL_HOST_USER")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",  # For development
        "LOCATION": "unique-snowflake",
    }
}

import os
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY", "pk_test_51PrMOk022pYe9ecpdIJZrF02yzDqrnDOeN2P9sl332gz7E8ROWanzXMLC8bxCsdfr0Q9RYMA4HlW9DrJ7Ddb8Efd009DsHMF5m")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "sk_test_51PrMOk022pYe9ecpXH0ddfGPxXmhJfIqc1JcDUWkaO7ERV4w4dmAAw1PNaQ5vB6VRclqhCr49lnTHkXdA9lN0DVk00YP0oVX91")

# Channels
ASGI_APPLICATION = "Nexo.asgi.application"
# Configure Redis as Channel Layer Backend
# settings.py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",  # Use Redis for production
    },
}

TIME_ZONE = 'Asia/Kolkata'  # India Standard Time (UTC+5:30)
USE_TZ = True  # Keep this True for timezone-aware datetime

# Chat encryption settings
import os
import base64
from dotenv import load_dotenv

load_dotenv()
AES_SECRET_KEY = "mUdV9wJqqWS7swqOJwlnlPOxKwIvbE57ujk7hQflYLs="  # 32 bytes key for AES-256
AES_SECRET_KEY = base64.b64decode(AES_SECRET_KEY)  # Decode the base64 key

# Celery settings

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis must be running
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'






